### ISSUE TITLE
ui_flow_control.R failing

### ISSUE THREAD

**Issue by cimentadaj** [timriffe/ODAPbackend#26]
@TTRustam I'm just running ui_flow_control.R from your master branch and got this error:

```
lt_output <-
+   lt_flexible(data_new, # required to have Age, Deaths, Exposures
+             # recall all of these are passed in from the app, which will contain
+             # its own default values.
+             OAnew      = 100,               # basic
+             age_out    = "single",          # basic
+             extrapFrom = 80,                # advanced
+             extrapFit  = data_in$Age[data_in$Age >= 60],  # advanced
+             extrapLaw  = NULL,              # advanced
+             radix      = 1e+05,             # advanced
+             SRB        = 1.05,              # advanced
+             a0rule     = "ak",              # advanced
+             axmethod   = "un",              # advanced
+             Sex        = "m")               # basic
Error in `reframe()` at ODAPbackend/R/lifetables.R:94:3:
ℹ In argument: `lt_flexible_chunk(...)`.
ℹ In group 1: `.id = "all"`.
Caused by error in `lt_flexible_chunk()`:
! Can't subset `.data` outside of a data mask context.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by cimentadaj** [comment]
@TTRustam could you also update this .R file to reflect what the current "flow" is to input the data, perform some adjustments, pass in to lt_flexible and show some plots for an example with several groups? Meaning the `.id` column is not simply 1 group.

**Comment by TTRustam** [comment]
Good afternoon Jorge. I have fixed this problem. If there are any other problems please let me know, and I will fix them too))
Sorry, the problem was .data argument.
Let me see regarding the new flow now.

**Comment by TTRustam** [comment]
Hola Jorge. I have added a small workflow example to the repo called epdated_flow_example.R
Try it and let me know if it is what was expected.
Thanks!

**Comment by TTRustam** [comment]
Hola!

I was under the impression that we have decided that we expect there to be
a Sex variable by default. Some DemoTools function output will depend on
the underlying sex, so the function automatically finds the Sex variable
and works with it accordingly. I understand that Sex in the end will be
included in the .id variable, but there is no harm in having it internally
stored in an additional column right? In the end, .id might include more
info than just sex.
These functions take the argument named.".id" as an input, this name is
hard coded. The example I use here I did just to check if the functions are
working as expected.
I will also talk about this tomorrow with Tim and be back to you.

Best regards,
Rustam.

вт, 8 окт. 2024 г. в 16:17, Jorge Cimentada ***@***.***>:

**Comment by timriffe** [comment]
Hi Rustam,
let’s allow a sex arg to be passed in, to be overrided if there’s a useable
sex column in data_in. @cimentadaj probably the UI should only query sex if
not given in the data. Rustam, for that to work, we need a sec column
parser. Make sense?

**Comment by TTRustam** [comment]
fixed
