### ISSUE TITLE
check_data for groups

### ISSUE THREAD

**Issue by cimentadaj** [timriffe/ODAPbackend#28]
@TTRustam We should update check_data for when there are groups. For example, having ages duplicate because there are two sexes throws errors.

Something like `check_data(data_in, keys)`.

**Comment by TTRustam** [comment]
Good afternoon Jorge,

These functions were not updated to work with the .id. Yes, I will talk
tomorrow with Tim, I can update them in a correct order if need be, sure.

Best regards,
Rustam.

вт, 8 окт. 2024 г. в 19:01, Jorge Cimentada ***@***.***>:
