### ISSUE TITLE
lt_flexible takes ages after smoothing

### ISSUE THREAD

**Issue by cimentadaj** [timriffe/ODAPbackend#47]
The logic is the following. Deaths_pop_brazil is the original data from Brazil. I took that data and passed it through two smooth_flexible one for exposures and one for deaths. The result is a combined data frame of abridged ages for each group. Still has the same 162 groups but smoothed abridged. When I run lt_flexible on the original data it runs on 3-4 secs. When I run on the smoothed dataset, I haven't been able to get it to finish. I've left it over for 15 mins now.

[deaths_pop_Brazil.csv](https://github.com/user-attachments/files/18111067/deaths_pop_Brazil.csv).

[combined_data.csv](https://github.com/user-attachments/files/18111071/combined_data.csv)

```
library(tictoc)

original <- readr::read_csv("~/Downloads/deaths_pop_Brazil.csv") %>% ODAPbackend::create_groupid(c("Year", "Sex", "UF"))

smoothed <- readr::read_csv("~/Downloads/combined_data.csv")


tic()
orig <- lt_flexible(original)
toc()

tic()
smooth <- lt_flexible(smoothed)
toc()
```
```
> library(tictoc)
> > > library(ODAPbackend)
Loading required package: ggplot2
> > original <- readr::read_csv("~/Downloads/deaths_pop_Brazil.csv") %>% create_groupid(c("Year", "Sex", "UF"))
Rows: 16362 Columns: 6
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (1): Sex
dbl (5): Year, UF, Age, Exposures, Deaths

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
> > smoothed <- readr::read_csv("~/Downloads/combined_data.csv")
Rows: 3564 Columns: 9
── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Sex, .id_label
dbl (7): .id, Exposures, Age, Deaths, Rates, Year, UF

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
> + + > tic()
> orig <- lt_flexible(original)
> toc()
3.875 sec elapsed
```

**Comment by timriffe** [comment]
Hiya, yes this will be slow. It's due to PCLM being run 162 times. This is the graduation method we use inside the lifetable function if a user gives abridged data and wants single ages back. `lt_flexible(smoothed, age_out = "abridged")` runs just as fast as the `original` run, which was in single ages to start with and requires no PCLM graduation. This was the main computational bottleck in COVerAGE-DB a couple years back, and it's usually worth it to just let it run. Sorry, it'd be a bigger R&D to try to make `ungroup::pclm()` run faster. It might be possible to add a ticker or expected computation time?

**Comment by cimentadaj** [comment]
I see. Should this happen as well if the smoothing output was in single ages? Because just trying it out with single ages and it also takes ages.

**Comment by timriffe** [comment]
no, if input and output are both in single ages then PCLM is not invoked,
and calculations should be just as fast as abridged -> abridged.
