### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by cimentadaj** [timriffe/ODAPbackend#5]
Hey guys, seems `ODAP_backend` is not permitted as a package name in the DESCRIPTION. Can't do `install_github("timriffe/ODAP_backend")`. The repo name can still be `ODAP_backend`. Any change we could change the name of the package in DESCRIPTION? Perhaps `ODAP.backend`?

**Comment by timriffe** [comment]
hang on, I'm pounding through devtools::check() now, need to take a break, and will complete it later

**Comment by timriffe** [comment]
although you might see if I've got far enough to make it installable; package and repo now called `ODAPbackend`

**Comment by timriffe** [comment]
`devtools::check()` now returns no errors or warnings, so this shoul dbe installable. We just need to handle a large number of NOTEs from check(), mostly about usage of tidy code imply no global bindings, bleh, will get to that when there's some time
